#include <filesystem>
#include <fstream>
#include <iostream>
#include <regex>
#include <string>

namespace fs = std::filesystem;

fs::path detect_package_root(const fs::path& argv0) {
  fs::path p = fs::absolute(argv0).parent_path();
  for (;;) {
    if (fs::exists(p / "package.xml") && fs::exists(p / "samples")) {
      return p;
    }
    if (p == p.parent_path()) {
      break;
    }
    p = p.parent_path();
  }
  return fs::current_path();
}

int main(int argc, char** argv) {
  fs::path input;
  fs::path out_h;
  fs::path out_cpp;
  if (argc == 1) {
    const fs::path root = detect_package_root(argc > 0 ? argv[0] : ".");
    input = root / "samples" / "main_panel.ui";
    out_h = root / "samples" / "ui_main_panel.h";
    out_cpp = root / "samples" / "ui_main_panel.cpp";
  } else if (argc == 4) {
    input = argv[1];
    out_h = argv[2];
    out_cpp = argv[3];
  } else {
    std::cerr << "usage: uic <input.ui> <output.h> <output.cpp>\n";
    return 2;
  }

  std::ifstream in(input);
  if (!in) {
    std::cerr << "uic: cannot open input: " << input.string() << "\n";
    return 3;
  }

  std::string ui_name = "GeneratedUi";
  std::string line;
  std::regex class_re(R"(class\s*=\s*\"([A-Za-z_][A-Za-z0-9_]*)\")");
  while (std::getline(in, line)) {
    std::smatch m;
    if (std::regex_search(line, m, class_re)) {
      ui_name = m[1].str();
      break;
    }
  }

  fs::create_directories(out_h.parent_path());
  fs::create_directories(out_cpp.parent_path());

  std::ofstream h(out_h);
  std::ofstream cpp(out_cpp);
  if (!h || !cpp) {
    std::cerr << "uic: cannot write outputs\n";
    return 4;
  }

  h << "// generated by uic\\n";
  h << "#pragma once\\n\\n";
  h << "struct Ui_" << ui_name << " {\\n";
  h << "  const char* name = \"" << ui_name << "\";\\n";
  h << "};\\n";

  cpp << "// generated by uic\\n";
  cpp << "#include \"" << out_h.filename().string() << "\"\\n\\n";
  cpp << "const char* ui_name() {\\n";
  cpp << "  static Ui_" << ui_name << " ui;\\n";
  cpp << "  return ui.name;\\n";
  cpp << "}\\n";

  std::cout << "uic: generated " << out_h.string() << " and " << out_cpp.string() << "\n";
  return 0;
}
