#include <filesystem>
#include <fstream>
#include <iostream>
#include <regex>
#include <string>

namespace fs = std::filesystem;

fs::path detect_package_root(const fs::path& argv0) {
  fs::path p = fs::absolute(argv0).parent_path();
  for (;;) {
    if (fs::exists(p / "package.xml") && fs::exists(p / "samples")) {
      return p;
    }
    if (p == p.parent_path()) {
      break;
    }
    p = p.parent_path();
  }
  return fs::current_path();
}

int main(int argc, char** argv) {
  fs::path input;
  fs::path output;
  if (argc == 1) {
    const fs::path root = detect_package_root(argc > 0 ? argv[0] : ".");
    input = root / "samples" / "widget.h";
    output = root / ".intermediate" / "generated" / "widget.meta.cpp";
  } else if (argc == 3) {
    input = argv[1];
    output = argv[2];
  } else {
    std::cerr << "usage: moc <input.h> <output.meta.cpp>\n";
    return 2;
  }

  std::ifstream in(input);
  if (!in) {
    std::cerr << "moc: cannot open input: " << input.string() << "\n";
    return 3;
  }

  std::string class_name = "Unknown";
  std::string line;
  std::regex class_re(R"(^\s*class\s+([A-Za-z_][A-Za-z0-9_]*)\b)");
  while (std::getline(in, line)) {
    std::smatch m;
    if (std::regex_search(line, m, class_re)) {
      class_name = m[1].str();
      break;
    }
  }

  fs::create_directories(output.parent_path());
  std::ofstream out(output);
  if (!out) {
    std::cerr << "moc: cannot write output: " << output.string() << "\n";
    return 4;
  }

  out << "// generated by moc\\n";
  out << "#include <string>\\n\\n";
  out << "const char* " << class_name << "_meta_class() {\\n";
  out << "  return \"" << class_name << "\";\\n";
  out << "}\\n";

  std::cout << "moc: generated " << output.string() << " from " << input.string() << "\n";
  return 0;
}
