#include <filesystem>
#include <fstream>
#include <iostream>
#include <regex>
#include <string>

namespace fs = std::filesystem;

fs::path detect_package_root(const fs::path& argv0) {
  fs::path p = fs::absolute(argv0).parent_path();
  for (;;) {
    if (fs::exists(p / "package.xml") && fs::exists(p / "samples")) {
      return p;
    }
    if (p == p.parent_path()) {
      break;
    }
    p = p.parent_path();
  }
  return fs::current_path();
}

int main(int argc, char** argv) {
  fs::path input;
  fs::path out_h;
  fs::path out_cpp;
  if (argc == 1) {
    const fs::path root = detect_package_root(argc > 0 ? argv[0] : ".");
    input = root / "samples" / "app.rc";
    out_h = root / "samples" / "rc_app.h";
    out_cpp = root / "samples" / "rc_app.cpp";
  } else if (argc == 4) {
    input = argv[1];
    out_h = argv[2];
    out_cpp = argv[3];
  } else {
    std::cerr << "usage: rc <input.rc> <output.h> <output.cpp>\n";
    return 2;
  }

  std::ifstream in(input);
  if (!in) {
    std::cerr << "rc: cannot open input: " << input.string() << "\n";
    return 3;
  }

  std::string symbol = "IDS_APP_TITLE";
  std::string value = "Generated Resource";
  std::string line;
  std::regex str_re(R"(^\s*(IDS_[A-Za-z0-9_]+)\s+\"([^\"]+)\")");
  while (std::getline(in, line)) {
    std::smatch m;
    if (std::regex_search(line, m, str_re)) {
      symbol = m[1].str();
      value = m[2].str();
      break;
    }
  }

  fs::create_directories(out_h.parent_path());
  fs::create_directories(out_cpp.parent_path());

  std::ofstream h(out_h);
  std::ofstream cpp(out_cpp);
  if (!h || !cpp) {
    std::cerr << "rc: cannot write outputs\n";
    return 4;
  }

  h << "// generated by rc\\n";
  h << "#pragma once\\n\\n";
  h << "const char* resource_text();\\n";
  h << "constexpr const char* resource_symbol = \"" << symbol << "\";\\n";

  cpp << "// generated by rc\\n";
  cpp << "#include \"" << out_h.filename().string() << "\"\\n\\n";
  cpp << "const char* resource_text() {\\n";
  cpp << "  return \"" << value << "\";\\n";
  cpp << "}\\n";

  std::cout << "rc: generated " << out_h.string() << " and " << out_cpp.string() << "\n";
  return 0;
}
